### ISSUE TITLE
FR1. Connecting to your Spotify account through the login screen

### ISSUE THREAD

**Issue by kevinjzh** [WSU-4110/Nostalgify#1]
|FR1. Customers Greetings UI|
|---|
|**Goal**: The application will grab your Spotify account information, Libraries, songs and connect them to our application.
**Stakeholders:** General Spotify User|
| **Description:** When the user log into our application through his Spotify account all his songs and folders will be transported into our application. |
| **Origin:** Based on initial project specification document, team
members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/3/2024
| **Priority:** 10 |

**Comment by Kasataya** [comment]
I will be working on this feature with Audi on 2/3/2024 mostly pulling the API into the application.
